matrix:
  include:
    - language: go
      go: 
       - master
      script: go test ./main.go

    - language: node_js
      node_js:
        - 9.11.1
      cache:
       directories:
         - node_modules
      install:
          - git fetch --unshallow --all
          - yarn global add codecov
          - yarn
      script:
         - yarn run test && codecov

notifications:
  email: false