sudo: false
cache:
  directories:
    - node_modules

matrix:
  include:
    - language: go
      go:
      - master
      script:
      - go test ./main.go
      after_success:
      - bash <(curl -s https://codecov.io/bash)

    - language: node_js
      cache:
        yarn: true
      node_js:
      - '8.4'
      script:
      - npm test
      # env:
      # - NODE_ENV: feature/travis
    
    - language: android
      before_install:
      - nvm install 9
      - node --version
      install:
      - npm install
      android:
        components:
        - build-tools-23.0.1
        - android-23
        - extra-android-m2repository
        - extra-google-google_play_services
        - extra-google-m2repository
        - addon-google_apis-google-16
      script:
      - npm run ci

notifications:
  email: false