sudo: false
cache:
 directories:
  - node_modules
  
matrix:
  include:
    - language: go
      go: 
       - master
      script: 
       - go test ./main.go
      after_success:
       - bash <(curl -s https://codecov.io/bash)

    - language: node_js
      node_js:
        - 9.11.1
     before_install:
       - curl -o- -L https://yarnpkg.com/install.sh | bash
       - export PATH="$HOME/.yarn/bin:$PATH"
     # - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.8/nvm.sh | bash
     # - export NVM_DIR=~/.nvm
     # - source $HOME/.nvm/nvm.sh
     install:
       - npm install
       - npm install -g codecov
       - npm install lint
     script:
      - npm run test
      - codecov
      - npm run lint
      - npm test
     
    - language: android
      os: linux
      jdk: oraclejdk8
      sudo: required
      cache:
        directories:
          - $HOME/.yarn-cache
      before_install: 
          - nvm install 8.9.4
          - node --version
      android:
        components:
          - tools
          - platform-tools
          - build-tools-26.0.1
          - android-26
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-16
    #make some android tests
    #  script: 
    #      - npm start android

    - language: objective-c
      os: osx
      osx_image: xcode9.4
      xcode_sdk: iphonesimulator9.0
      node_js: false
      cache:
       directories:
        - bundler: true
        - cocoapods: true
        - yarn: true
        - $HOME/Library/Caches/Homebrew
      before_install: 
        - nvm install 8.9.4
        - node --version
      install:
        - gem install xcpretty
        
     #make some ios tests
     # script:
     #     - npm start ios
        
notifications:
  email: false
  
