before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

matrix:
  include:
  # testing golang backend
    - language: go
      go: 
       - master
      script: go test ./main.go

    - language: node_js
      node_js:
        - 9.11.1
      cache:
       directories:
         - node_modules
      script:
          - yarn run test && codecov
          - npm run lint
          - npm test
          - npm run build

    - language: android
      sudo: required
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.yarn-cache
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
      script: npm run android

    - language: objective-c
      osx_image: xcode9.4
      xcode_sdk: iphonesimulator9.0
      node_js: 8
      cache:
        bundler: true
        cocoapods: true
        yarn: true
        directories:
         - $HOME/Library/Caches/Homebrew
      before_script:
        - nvm install 8
        - sudo easy_install virtualenv
        - virtualenv ~/virtualenv
        - source ~/virtualenv/bin/activate
      script: npm run ios
        
notifications:
  email: false
  
